#!/bin/bash
# Copyright www.safedog.cn @ 2017
#

# Check if user is mybk
[ $(whoami) != "mybk" ] && { echo "ERROR: This script must be run as mybk"; exit 1; }

# Config File
# . /home/mybk/mybk.cfg &> /dev/null

CLICKHOUSE_HOME="/opt/clickhouse-server"

CHPROXY_SERVER_PID=$(ps ax -o pid= -o command= | grep -v grep | grep  chproxy | grep -v sdchproxy | awk '{print$1}')

start() {
         echo "Starting chproxy Server ..."
         nohup $CLICKHOUSE_HOME/bin/chproxy --config=$CLICKHOUSE_HOME/config.yml &> /sdyunlei/logs/clickhouse/chproxy.log &
}

stop() {
     if [[ -n $CHPROXY_SERVER_PID ]]; then
         echo "Stopping CHPROXY SERVER ..."
         kill -9 $CHPROXY_SERVER_PID
     else
         echo "CHPROXY SERVER is not running"
     fi
}

restart() {
    stop
    start
}

status() {
     if [[ -n $CHPROXY_SERVER_PID ]]; then
         echo "CHPROXY SERVER is runing"
     else
         echo "CHPROXY SERVER is not running"
     fi
}

usage() {
    echo "Usage: $(basename $0) {start|stop|restart|status}"
}

[ $# -eq 0 ] && usage

case "$1" in
    "start")
        start
        ;;
    "stop")
        stop
        ;;
    "restart")
        restart
        ;;
    "status")
        status
        ;;
    "-h")
        usage
        ;;
esac
