#!/bin/bash
# Copyright www.safedog.cn @ 2017
# by 1057 (lvxj@safedog.cn)

# Check if user is mybk
[ $(whoami) != "mybk" ] && { echo "ERROR: This script must be run as mybk"; exit 1; }

# Config File
. /home/mybk/mybk.cfg &> /dev/null

CLICKHOUSE_HOME="/opt/clickhouse-server"

CLICKHOUSE_SERVER_PID=$(ps ax -o pid= -o command= | grep -v grep | grep  clickhouse | awk '{print$1}')

start() {
         echo "Starting Clickhouse Server ..."
         $CLICKHOUSE_HOME/bin/clickhouse-server start
}

stop() {
     if [[ -n $CLICKHOUSE_SERVER_PID ]]; then
         echo "Stopping Clickhouse Server ..."
         $CLICKHOUSE_HOME/bin/clickhouse-server stop
     else
         echo "Clickhouse Server is not running"
     fi
}

restart() {
    stop
    start
}

status() {
    $CLICKHOUSE_HOME/bin/clickhouse-server status
}

usage() {
    echo "Usage: $(basename $0) {start|stop|restart|status}"
}

[ $# -eq 0 ] && usage

case "$1" in
    "start")
        start
        ;;
    "stop")
        stop
        ;;
    "restart")
        restart
        ;;
    "status")
        status
        ;;
    "-h")
        usage
        ;;
esac
