#!/bin/bash
# Copyright www.safedog.cn @ 2017
# by 1057 (lvxj@safedog.cn)

# Check if user is mybk
[ $(whoami) != "mybk" ] && { echo "ERROR: This script must be run as mybk"; exit 1; }

yunlei_version=${yunlei_version:-3}
. /home/mybk/mybk.cfg &> /dev/null

jpidof() {
    for i in "$@"; do
        ps aux | sed 's/start$//' | awk '$11~/java$/&&$NF~/\y'$i'\y/{print$2}'
    done
}

wait_safemode_off() {
    echo -n "Waiting for Safe mode turned off."
    while true; do
        if /opt/hadoop/bin/hadoop dfsadmin -safemode get 2> /dev/null | grep OFF > /dev/null; then
            echo; break
        else
            echo -n .; sleep 1
        fi
    done
}

start() {
    case "$yunlei_version" in
        2*)
            if [[ -n $(jpidof NameNode DataNode SecondaryNameNode TaskTracker JobTracker) ]]; then
                echo "Hadoop already started."
            else
                /opt/hadoop/bin/start-all.sh
            fi
            ;;
        3*)
            if [[ -n $(jpidof NameNode DataNode SecondaryNameNode) ]]; then
                echo "Hadoop already started."
            else
                 /opt/hadoop/sbin/start-dfs.sh
            fi
            ;;
    esac
    wait_safemode_off
}

stop() {
    case "$yunlei_version" in
        2*) /opt/hadoop/bin/stop-all.sh;;
        3*) /opt/hadoop/sbin/stop-dfs.sh;;
    esac
}

restart() {
    stop
    start
}

status() {
    if [[ ${yunlei_version:0:1} == 3 ]]; then
        for i in NameNode SecondaryNameNode DataNode; do jps | grep "[0-9]\+ $i$" || echo Not Found: $i; done
    else
        for i in NameNode SecondaryNameNode TaskTracker DataNode JobTracker; do jps | grep "[0-9]\+ $i$" || echo Not Found: $i; done
    fi
}

usage() {
    echo "Usage: $(basename $0) {start|stop|restart|status}"
}

[ $# -eq 0 ] && usage

case "$1" in
    "start")
        start
        ;;
    "stop")
        stop
        ;;
    "restart")
        restart
        ;;
    "status")
        status
        ;;
    "-h")
        usage
        ;;
esac
