#!/bin/bash
# Copyright www.safedog.cn @ 2017
# by 1057 (lvxj@safedog.cn)

# Check if user is mybk
[ $(whoami) != "mybk" ] && { echo "ERROR: This script must be run as mybk"; exit 1; }

start() {
    if [[ -n $(pidof nginx) ]]; then
        echo "Nginx already started."
    else
        echo "Starting Nginx."
        sudo /usr/local/nginx/sbin/nginx
    fi
}

stop() {
    if [[ -n $(pidof nginx) ]]; then
        echo "Shutting down Nginx."
        sudo /usr/local/nginx/sbin/nginx -s stop
    else
        echo "Nginx already stopped."
    fi
}

restart() {
    stop
    start
}

status() {
    if [[ -n $(pidof nginx) ]]; then
        echo "Nginx running ($(pidof nginx))"
    else
        echo "Nginx is not running"
        return 1
    fi
}

reload() {
    if [[ -n $(pidof nginx) ]]; then
        sudo /usr/local/nginx/sbin/nginx -s reload
    else
        echo "Nginx is not running"
        return 1
    fi
}

usage() {
    echo "Usage: $(basename $0) {start|stop|restart|status|reload}"
}

[ $# -eq 0 ] && usage

case "$1" in
    "start")
        start
        ;;
    "stop")
        stop
        ;;
    "restart")
        restart
        ;;
    "status")
        status
        ;;
    "reload")
        reload
        ;;
    "-h")
        usage
        ;;
esac
