#!/bin/bash
# Copyright www.safedog.cn @ 2017
# by 1057 (lvxj@safedog.cn)

# Check if user is mybk
[ $(whoami) != "mybk" ] && { echo "ERROR: This script must be run as mybk"; exit 1; }

if [[ -x /opt/phoenix/bin/queryserver.py ]]; then
    PHOENIX_EXEC=/opt/phoenix/bin/queryserver.py
elif [[ -x /opt/apache-phoenix-4.13.1-HBase-1.3-bin/bin/queryserver.py ]]; then
    PHOENIX_EXEC=/opt/apache-phoenix-4.13.1-HBase-1.3-bin/bin/queryserver.py
else
    echo "ERROR: phoenix not found."
    exit 1
fi

start() {
    $PHOENIX_EXEC start
}

stop() {
    $PHOENIX_EXEC stop
}

restart() {
    stop
    start
}

status() {
    for i in QueryServer; do jps | grep "[0-9]\+ $i$" || echo Not Found: $i; done
}

usage() {
    echo "Usage: $(basename $0) {start|stop|restart|status}"
}

[ $# -eq 0 ] && usage

case "$1" in
    "start")
        start
        ;;
    "stop")
        stop
        ;;
    "restart")
        restart
        ;;
    "status")
        status
        ;;
    "-h")
        usage
        ;;
esac
