#!/bin/bash
# Copyright www.safedog.cn @ 2017
# by 1057 (lvxj@safedog.cn)

# Check if user is mybk
[ $(whoami) != "mybk" ] && { echo "ERROR: This script must be run as mybk"; exit 1; }

. /home/mybk/mybk.cfg &> /dev/null

start() {
    cd /opt/zookeeper
    /opt/zookeeper/bin/zkServer.sh start
}

stop() {
    cd /opt/zookeeper
    /opt/zookeeper/bin/zkServer.sh stop
}

restart() {
    stop
    start
}

status() {
    if echo ruok | nc localhost 2181 &> /dev/null; then
        echo "ZooKeeper is running"
        echo stat | nc localhost 2181 | grep Mode:
    else
        echo "ZooKeeper is not running"
    fi
}

usage() {
    echo "Usage: $(basename $0) {start|stop|restart|status}"
}

[ $# -eq 0 ] && usage

case "$1" in
    "start")
        start
        ;;
    "stop")
        stop
        ;;
    "restart")
        restart
        ;;
    "status")
        status
        ;;
    "-h")
        usage
        ;;
esac
